### ISSUE TITLE
Super Mario Bros Deluxe not working

### ISSUE THREAD

**Issue by DynamicThijs** [tswilliamson/prizoop#2]
Hey,

When I try to launch SMBD, I get an Exited (-1), press [MENU] notice on top of my screen. I also get an Undefined instruction 0x error. If I then want to return to the ROM menu, I have to take out the batteries of my FX-CG50 and put them back in. Zelda however works fine.

Can you fix this?
Thanks in advance!

**Comment by DynamicThijs** [comment]
OK somehow I managed to get it working, but the goomba textures are at different locations than it's hitboxes..

**Comment by MattIPv4** [comment]
Having the same issue :(
