### ISSUE TITLE
Crash Zelda Oracle of seasons

### ISSUE THREAD

**Issue by maxou31530** [tswilliamson/prizoop#3]
Hi !
When I play this game, a room of the Dungeon n°2 of Snakes ruins (the 2nd room, in the line of entrace) is buged. This room crash the game and emulator.
(Sorry for bad english, i'm french)
Do you have an idea about this problem ?

**Comment by Micker003** [comment]
Maybe a little late, but certain games require a certain clockspeed. Download Pover (a clockspeed manager for the calculator), and set the clockspeed 2 increments higher, to about 74 MHz. This fixes the issue in LOZ OoS
