### ISSUE TITLE
game not found

### ISSUE THREAD

**Issue by gsandeep27** [tswilliamson/prizoop#4]
Loading file "Rom Name"
Not found -1

Above is a error message that appears after running the rom
Again if i go to rom menu and run the rom this system error appears:

I am getting a system error which mentions tlb error.
target=0c103efc
pc=020018c0

Then I press exit to restart the calculator

My calculator: Casio FX-CG50

**Comment by rekonga** [comment]
I get this error constantly too.

**Comment by gsandeep27** [comment]
i did'nt even play a game with prizoop yet.

**Comment by SamySensei** [comment]
This problem is simple to solve, the rom of the game must not exceed 12 characters. (sorry for my english)

**Comment by qqeevv** [comment]
> This problem is simple to solve, the rom of the game must not exceed 12 characters. (sorry for my english)

Thank you! Problem solved!

**Comment by mustafi38** [comment]
But how can i solve the problem?? What i have to do???

**Comment by SamySensei** [comment]
Rename the game on your computer (any name) and be careful that it does not exceed 12 characters and it will normally works.

**Comment by mustafi38** [comment]
What do you named it? I named it pokemon.gb and it is still not working. (File not found)

**Comment by jmuller2002** [comment]
I am having an error like this even though the name is less than 12 characters

System ERROR
REBOOT:        [EXIT]
INITIALIZE:     [EXE]
   TLB ERROR
   TARGET=0C103EFC
   PC=00000060

Prizoop is running on a casio fx cg-20 with os system 3.11

**Comment by tswilliamson** [comment]
As stated in the readme: "The filenames for these files should be simple and less than 12 characters, such as MyGame.gbc."

Another reason this can happen is if you have named a gameboy color game ".gb" instead of ".gbc" or vice versa.
