### ISSUE TITLE
Not able to compile prizoop on Arch (and Windows)

### ISSUE THREAD

**Issue by SapphireOmega** [tswilliamson/prizoop#5]
Hi, I am running Arch Linux and I have been trying to compile prizoop for the fxcg-50, but I haven't been able to succeed. 

Firstly, I downloaded libfxcg and the PrizmSDK-v0.3 from GitHub and built libfxcg using the slightly outdated sh3eb-elf-binutils and sh3eb-elf-gcc packages from the AUR by changing the TOOLCHAIN_PREFIX variables in libfxcg/libfxcg/Makefile and libfxcg/libc/Makefile from prizm- to sh3eb-elf-. Then I copied the contents from libfxcg/include and libfxcg/lib to PrizmSDK-v0.3/include and PrizmSDK-v0.3/lib. 

After that, I downloaded prizoop, calctype and prizm-zx7 from GitHub and put them in the PrizmSDK-v0.3/projects directory. Then I changed the FXCGSDK environment variable to absolute path of the PrizmSDK-v0.3 directory and tried to run make inside the PrizmSDK-v0.3/projects/prizoop directory, but nothing happened and the output I got was: "rm -f -rf <path to the PrizmSDK>/projects/prizloop/prizloop.bin <path to the PrizmSDK>/projects/prizloop/prizloop.g3a." It seemed like if something went wrong and it ran "make clean". I confirmed this by removing the clean line from the Makefile and running make again, because this time it said: "make: Nothing to be done for 'clean'." I've also tried changing the BUILD and TARGET variables in the Makefile, but I would just get an empty folder. I think something might have gone wrong with patching the SDK with libfxcg, but I'm not sure what the problem is.

I would like to thank you in advance.

NOTE: A friend of mine has also been trying to builld prizoop, but on windows, using cygwin, but he too wasn't able to succeed.

**Comment by Game4all** [comment]
Hello, 
I managed to build prizoop from the command line with the patched PrizmSDK v0.3 on Windows (7-x64) by looking into the visual studio vcproj file.

![vcprojcmdline](https://user-images.githubusercontent.com/20256717/46581485-e6449100-ca39-11e8-811d-db61d6bdf03f.PNG)

The following command builds successfully prizoop in release mode

```
make.bat DEFINES="-DTARGET_PRIZM=1 -DDEBUG=0" CONFIG=DeviceRelease"
```

But the compiled addin crashes with the following error code when i run it on my fxcg-50:
![err](https://user-images.githubusercontent.com/20256717/46581540-a6ca7480-ca3a-11e8-89ee-5bde9948de66.png)

Any ideas about it ?
Cheers.

**Comment by slapjd** [comment]
@Game4all Did you ever figure out how to compile this in a way that works? I'm getting a similar error when I compile it on windows too

**Comment by Game4all** [comment]
I still haven't been able to get a working version

**Comment by slapjd** [comment]
For anyone reading trying to compile in the future:
if you are getting an error similar to Game4all's above, try disabling compiler optimisations (change -Os to -O0 in the makefiles) for libfxcg before patching the sdk. Doing that seemed to fix the problem on my fx-CG50

**Comment by Game4all** [comment]
I'll try out that later when I'll get access to a w7 machine

**Comment by tswilliamson** [comment]
I've made all of this hopefully resolved with the latest commit and providing my version of the SDK, let me know if this works for you and I will close the issue!
