### ISSUE TITLE
TLB Errors

### ISSUE THREAD

**Issue by Ception8** [tswilliamson/prizoop#6]
Hello!

I have been trying to get Prizoop working on my fx-CG50. However, when I start a ROM, it doesn't load, and when I click on something else, I am given the error message:

System ERROR
REEBOOT   : [EXIT]
INITIALIZE  : [EXE]
TLB ERROR
TARGET = 6B1CAC2C
PC = 00000003

I then click exit, and go through the menu. 

Is there any way that I might be able to fix this? The ROM I am using is Pokémon Rouge if that makes a difference.

**Comment by snakeBumble** [comment]
Yeah i also have the fx-CG50 and get the same Error Message.

**Comment by Game4all** [comment]
I own a fx-CG50 too and i've been able to tackle the problem by first loading another rom, then going to the rom selection menu and launching pokemon. I hope it'll work for you

**Comment by snakeBumble** [comment]
No it doesnt work unfortunately. When I press f6 which would play the game it says at the bottom that no save file is in system.

**Comment by wackadoo432** [comment]
Which game did you use to make it work?

**Comment by Game4all** [comment]
Should work with any game as long as it's not Pokemon

**Comment by wackadoo432** [comment]
Didn't work with Mario but I got it working with Zelda, cheers.

**Comment by Lerx1** [comment]
I found if the occurs after trying to launch, click f6 once to obtain the data then click f5 then f6 again then works fine.

**Comment by tswilliamson** [comment]
As stated in the readme: "The filenames for these files should be simple and less than 12 characters, such as MyGame.gbc."

Another reason this can happen is if you have named a gameboy color game ".gb" instead of ".gbc" or vice versa.
