### ISSUE TITLE
Pokémon Red

### ISSUE THREAD

**Issue by CRVLH8** [tswilliamson/prizoop#8]
Hello. I installed the emulator today and I tried Pokémon Crystal and Red. Crystal worked fine but Red isn't working for some reason.
When i try loading the rom (name: "P.Red.gb") i get 
![NotFound](https://user-images.githubusercontent.com/58441408/69995725-887ddd00-1548-11ea-8713-7fd2d9a62abc.jpg)
 and when i try it for the second time i get System Error 
![SysError](https://user-images.githubusercontent.com/58441408/69995819-b531f480-1548-11ea-926d-0e1615ea15cf.jpg)
The emulator works for both GB and GBC games right?
Thank you.

(pokémon crystal is named "P.Crystal.gbc")

**Comment by aviwad** [comment]
rename it p.gbc, maybe the two dots is confusing it?

**Comment by tswilliamson** [comment]
Yeah they are not following the file name conventions for sure.
